Fix issue #621: Catch libvirt exception when network does not have bridge name
The bridged network does not have a bridge name (<bridge> on XML)

<network>
  <name>bridged</name>
  <uuid>70441e61-2f87-44c4-836b-5cc817fcf025</uuid>
  <forward dev='eth0' mode='bridge'>
    <interface dev='eth0'/>
  </forward>
</network>

and then libvirt raises an exception when we try to get the bridge name.

File "/usr/lib64/python2.7/site-packages/libvirt.py", line 2780, in bridgeName
if ret is None: raise libvirtError ('virNetworkGetBridgeName() failed', net=self)
libvirtError: internal error: network 'bridged-eth0' does not have a bridge name.

Signed-off-by: Aline Manera <alinefm@linux.vnet.ibm.com>