Bug fix: Do not allow user selects invalid volume format to create a new volume
When trying to create a volume with one of the formats: bochs, cloop, cow, dmg -
an error is raised by libvirt as listed below:

[alinefm@alinefm-TP440 kimchi]$ sudo virsh vol-create default bochs.xml
error: internal error: Child process (/usr/bin/qemu-img create -f bochs
/var/lib/libvirt/images/fedora231462484883854.img 1K) unexpected exit
status 1: qemu-img: /var/lib/libvirt/images/fedora231462484883854.img:
Format driver 'bochs' does not support image creation

[alinefm@alinefm-TP440 kimchi]$ sudo virsh vol-create default cloop.xml
error: internal error: Child process (/usr/bin/qemu-img create -f cloop
/var/lib/libvirt/images/fedora231462484883854.img 1K) unexpected exit
status 1: qemu-img: /var/lib/libvirt/images/fedora231462484883854.img:
Format driver 'cloop' does not support image creation

[alinefm@alinefm-TP440 kimchi]$ sudo virsh vol-create default cow.xml
error: internal error: Child process (/usr/bin/qemu-img create -f cow
/var/lib/libvirt/images/fedora231462484883854.img 1K) unexpected exit
status 1: qemu-img: /var/lib/libvirt/images/fedora231462484883854.img:
Unknown file format 'cow'

[alinefm@alinefm-TP440 kimchi]$ sudo virsh vol-create default dmg.xml
error: internal error: Child process (/usr/bin/qemu-img create -f dmg
/var/lib/libvirt/images/fedora231462484883854.img 1K) unexpected exit
status 1: qemu-img: /var/lib/libvirt/images/fedora231462484883854.img:
Format driver 'dmg' does not support image creation

To prevent this error, do not allow user to selects one of those invalid
formats.

Signed-off-by: Aline Manera <alinefm@linux.vnet.ibm.com>