GET /plugins failed, fix it
commit 478d01d add a more parameter "filter_params" for get method of collection.

But it does not add this new parameter to derived class.

$ curl -H "Content-Type: application/json" -H "Accept: application/json" \
http://localhost:8000/plugins

Error as follow:

[27/Jan/2014:23:01:50] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line
656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line
188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line
34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/shhfeng/work/workdir/kimchi/src/kimchi/control/base.py",
line 266, in index
    return self.get(filter_params)
TypeError: get() takes exactly 1 argument (2 given)

Signed-off-by: ShaoHe Feng <shaohef@linux.vnet.ibm.com>