bug fix: two python souce missing in distribution
kimchi complains about module utils and cachebust

Traceback (most recent call last):
File "/usr/bin/kimchid", line 31, in <module>
import kimchi.server
File "/usr/lib/python2.7/site-packages/kimchi/server.py", line 30, in <module>
import model
File "/usr/lib/python2.7/site-packages/kimchi/model.py", line 36, in <module>
import vmtemplate
File "/usr/lib/python2.7/site-packages/kimchi/vmtemplate.py", line 27, in <module>
import isoinfo
File "/usr/lib/python2.7/site-packages/kimchi/isoinfo.py", line 27, in <module>
from utils import kimchi_log
ImportError: No module named utils

[03/Sep/2013:21:36:32] HTTP Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
response.body = self.handler()
File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
self.body = self.oldhandler(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
return self.callable(*self.args, **self.kwargs)
File "/usr/lib/python2.7/site-packages/kimchi/controller.py", line 142, in index
return self.get()
File "/usr/lib/python2.7/site-packages/kimchi/root.py", line 54, in get
return self.default('kimchi-ui.html')
File "/usr/lib/python2.7/site-packages/kimchi/root.py", line 59, in default
return template.render(page, None)
File "/usr/lib/python2.7/site-packages/kimchi/template.py", line 90, in render
return Template(file=filename, searchList=params).respond()
File "/usr/lib64/python2.7/site-packages/Cheetah/Template.py", line 1259, in
__init__
self._compile(source, file, compilerSettings=compilerSettings)
File "/usr/lib64/python2.7/site-packages/Cheetah/Template.py", line
1553, in _compile
keepRefToGeneratedCode=True)
File "/usr/lib64/python2.7/site-packages/Cheetah/Template.py",
line 788, in compile
exec(co, mod.__dict__)
File "_usr_share_kimchi_ui_pages_kimchi_ui_html_tmpl.py",
line 27, in <module>
ImportError: No module named cachebust

Signed-off-by: apporc <appleorchard2000@gmail.com>