Bug fix: Create VM based on Remote ISO Template
When trying to create a VM from a recent created remote ISO Template, an error
was raised:

Error in async_task 1
Traceback (most recent call last):
  File "/home/alinefm/wok/src/wok/asynctask.py", line 72, in _run_helper
    self.fn(cb, opaque)
  File "/home/alinefm/wok/src/wok/plugins/kimchi/model/vms.py", line 168, in _create_task
    vol_list = t.fork_vm_storage(vm_uuid)
  File "/home/alinefm/wok/src/wok/plugins/kimchi/model/templates.py", line 397, in fork_vm_storage
    vol_list = self.to_volume_list(vm_uuid)
  File "/home/alinefm/wok/src/wok/plugins/kimchi/vmtemplate.py", line 262, in to_volume_list
    base_fmt = imageinfo.probe_img_info(d['base'])['format']
  File "/home/alinefm/wok/src/wok/plugins/kimchi/imageinfo.py", line 40, in probe_img_info
    info['actual-size'] = info['actual-size'] >> 30
KeyError: 'actual-size'

It was because the remote ISO path was being set as CDROM and also as
base image, causing the issue when creating the VM.

Fix it.

Signed-off-by: Aline Manera <alinefm@linux.vnet.ibm.com>