bug fix: Make sure to use string with os.walk
When kimchi is installed in the system, deep scan failed with the following
error:

Error in async_task 1
Error in async_task 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/kimchi/asynctask.py", line 70, in _run_helper
    self.fn(cb, opaque)
  File "/usr/lib/python2.7/dist-packages/kimchi/scan.py", line 87, in start_scan
    probe_iso(None, scan_params)
  File "/usr/lib/python2.7/dist-packages/kimchi/isoinfo.py", line 290, in probe_iso
    for root, dirs, files in os.walk(loc):
  File "/usr/lib/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)

It is because os.walk expect a string and kimchi is using unicode.
So encode the path before call os.walk to avoid this problem.

Signed-off-by: Aline Manera <alinefm@br.ibm.com>