Fix storage volume clone test case
Commit c9ea5072b changed the target_uri of a cloning storage volume to
distinguish it from a storage volume creation by appeding '/clone' to
the end of the target_uri. But the test case was not properly updated.
So do that to avoid issues while running 'make check'.

Without this patch a test case is failing:

[alinefm@alinefm-TP440 tests]$ sudo ./run_tests.sh test_mock_storagevolume.MockStorageVolumeTests.test_storagevolume
***** Running unit test:
test_mock_storagevolume.MockStorageVolumeTests.test_storagevolume...
FAILED
======================================================================
FAIL: test_storagevolume
(test_mock_storagevolume.MockStorageVolumeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mock_storagevolume.py", line 99, in test_storagevolume
    _do_volume_test(self, model, host, ssl_port, pool_name)
  File "test_model_storagevolume.py", line 141, in _do_volume_test
    self.assertEquals(200, resp.status)
AssertionError: 200 != 404

----------------------------------------------------------------------

Signed-off-by: Aline Manera <alinefm@linux.vnet.ibm.com>