issue #143: Add missing parameter while calling the request error handler
Commit 114d52ed added 'originalError' functionality but while calling the error
handler any parameter is passed.

The XMLHttpRequest object is expected as parameter to error handler in order to
display the error message.

Without XMLHttpRequest parameter any error message is displayed and Firebug
shows:
    TypeError: err is undefined
    kimchi.message.error(err.responseJSON.reason);

Signed-off-by: Aline Manera <alinefm@br.ibm.com>