bug fix: Allow user to get guest console (noVNC and spice)
While trying to access the guest console a Jquery error was displayed:

TypeError: $.base64 is undefined
    return $.base64.btoa(str, true).replace(/\+/g, '-').replace(/\//g, '_');

It is because the base64/jquery.base64.js was conflicting with the new Jquery
version.

Signed-off-by: Aline Manera <alinefm@linux.vnet.ibm.com>