Use dedicate function to remove unused namespace
c5cb1515 used "cleanup_namespaces=True" to clean unused namespace.
But on rhel lxml library, this argument is not supported and result
in error:
File "./src/kimchi/model/utils.py", line 145,
        in _kimchi_get_metadata_node
    objectify.deannotate(kimchi, cleanup_namespaces=True)
  File "lxml.objectify.pyx", line 1728,
      in lxml.objectify.deannotate (src/lxml/lxml.objectify.c:17914)
TypeError: deannotate() got an unexpected keyword argument 'cleanup_namespaces'

So use a dedicate function to clean the unused namespace.

Signed-off-by: Royce Lv <lvroyce@linux.vnet.ibm.com>