issue #454: Properly display storage volumes in a pool with sub-directories
Kimchi controller allows filterting the resources according to their
parameters, but the filter data type may vary: string, list, regex.

When using re.match() to validate the regex we need to make sure the value
is a string, otherwise we will face the error:

File "/usr/lib64/python2.6/re.py", line 137, in match
   return _compile(pattern, flags).match(string)
File "/usr/lib64/python2.6/re.py", line 232, in _compile
   p = _cache.get(cachekey)
TypeError: unhashable type: 'list'

Signed-off-by: Aline Manera <alinefm@linux.vnet.ibm.com>