Fix snapshots test case
Commit a2063007 has added a new test to validate snapshot on running
guest but it has not considered the whole test case in count and it was
failing as below:

======================================================================
FAIL: test_vm_lifecycle (test_model.ModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_model.py", line 218, in test_vm_lifecycle
    self.assertEquals({}, empty_snap)
AssertionError: {} != {'state': u'running', 'name': u'1486470484', 'parent': u'', 'created': u'1486470 [truncated]...
- {}
+ {'created': u'1486470484',
+  'name': u'1486470484',
+  'parent': u'',
+  'state': u'running'}

So fix it.

Signed-off-by: Aline Manera <alinefm@linux.vnet.ibm.com>