bug fix: make gen-pot scan multi lines
let cheetah generate python file then xgettext can scan python directly

it is easy to generate the kimchi.pot by cheetah and xgettext.
$ cheetah compile *.tmpl -p | xgettext --no-location -o kimchi.pot -L Python -

But cheetah compile require the input files be named according to the same rules as Python modules.
For example:
$ cheetah compile storagepool-add.html.tmpl -p
Traceback (most recent call last):
  File "/usr/bin/cheetah", line 3, in <module>
    _cheetah()
  File "/usr/lib64/python2.7/site-packages/Cheetah/CheetahWrapper.py", line 620, in _cheetah
    CheetahWrapper().main()
  File "/usr/lib64/python2.7/site-packages/Cheetah/CheetahWrapper.py", line 148, in main
    meth()
  File "/usr/lib64/python2.7/site-packages/Cheetah/CheetahWrapper.py", line 231, in compile
    self._compileOrFill()
  File "/usr/lib64/python2.7/site-packages/Cheetah/CheetahWrapper.py", line 380, in _compileOrFill
    self._compileOrFillBundle(b)
  File "/usr/lib64/python2.7/site-packages/Cheetah/CheetahWrapper.py", line 591, in _compileOrFillBundle
    be named according to the same rules as Python modules.""" % tup)
Cheetah.CheetahWrapper.Error: storagepool-add.html: base name storagepool-add.html.tmpl contains invalid
characters.  It must be named according to the same rules as Python modules.

So this just cat every tmpl file to std out, and let cheetah compile it.

Signed-off-by: ShaoHe Feng <shaohef@linux.vnet.ibm.com>