Fix SLES version checking in interfaces.py
This patch fixes a bug in interfaces.py. A parenthesis is missing, so
when the user tries to create a SLES ppc64 guest, kimchi is going to
raise the error:
AttributeError: 'unicode' object has no attribute 'version'

Signed-off-by: Rodrigo Trujillo <rodrigo.trujillo@linux.vnet.ibm.com>